apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: chimi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chimi-deploy
  template:
    metadata:
      labels:
        app: chimi-deploy
    spec:
      containers:
      - image: cloudsihmar/takin:latest
        name: pet
